parameters:
# xrowmetadata
    xrow_field_types.xrowmetadata.class: xrow\FieldTypesBundle\FieldType\XrowMetadata\Type
    xrow_field_types.xrowmetadata.converter.class: xrow\FieldTypesBundle\FieldType\XrowMetadata\XrowMetadataConverter

# xrowformgenerator
    xrow_field_types.xrowformgenerator.class: xrow\FieldTypesBundle\FieldType\XrowFormGenerator\Type
    xrow_field_types.xrowformgenerator.converter.class: xrow\FieldTypesBundle\FieldType\XrowFormGenerator\XrowFormGeneratorConverter

# recaptcha
    xrow_field_types.recaptcha.class: xrow\FieldTypesBundle\FieldType\ReCaptcha\Type
    xrow_field_types.recaptcha.converter.class: xrow\FieldTypesBundle\FieldType\ReCaptcha\ReCaptchaConverter

# xrowgis
    xrow_field_types.xrowgis.class: xrow\FieldTypesBundle\FieldType\XrowGis\Type
    xrow_field_types.xrowgis.converter.class: xrow\FieldTypesBundle\FieldType\XrowGis\XrowGisConverter
    xrow_field_types.xrowgis.externalStorage.class: xrow\FieldTypesBundle\FieldType\XrowGis\XrowGisStorage
    xrow_field_types.xrowgis.storage_gateway.class: xrow\FieldTypesBundle\FieldType\XrowGis\XrowGisStorage\Gateway\LegacyStorage

# hmregexpline
    xrow_field_types.hmregexpline.class: xrow\FieldTypesBundle\FieldType\Regexpline\Type
    xrow_field_types.hmregexpline.converter.class: xrow\FieldTypesBundle\FieldType\Regexpline\RegexplineConverter

# xrownoderelation
    xrow_field_types.xrownoderelation.class: xrow\FieldTypesBundle\FieldType\XrowNodeRelation\Type
    xrow_field_types.xrownoderelation.converter.class: xrow\FieldTypesBundle\FieldType\XrowNodeRelation\XrowNodeRelationConverter

services:
# xrowmetadata
    xrow_field_types.xrowmetadata:
        class: %xrow_field_types.xrowmetadata.class%
        parent: ezpublish.fieldType
        tags:
            - {name: ezpublish.fieldType, alias: xrowmetadata}
    xrow_field_types.xrowmetadata.converter:
        class: %xrow_field_types.xrowmetadata.converter.class%
        tags:
            - {name: ezpublish.storageEngine.legacy.converter, alias: xrowmetadata}

# xrowformgenerator
    xrow_field_types.xrowformgenerator:
        class: %xrow_field_types.xrowformgenerator.class%
        parent: ezpublish.fieldType
        tags:
            - {name: ezpublish.fieldType, alias: xrowformgenerator}
    xrow_field_types.xrowformgenerator.converter:
        class: %xrow_field_types.xrowformgenerator.converter.class%
        tags:
            - {name: ezpublish.storageEngine.legacy.converter, alias: xrowformgenerator}

# recaptcha
    xrow_field_types.recaptcha:
        class: %xrow_field_types.recaptcha.class%
        parent: ezpublish.fieldType
        tags:
            - {name: ezpublish.fieldType, alias: recaptcha}
    xrow_field_types.recaptcha.converter:
        class: %xrow_field_types.recaptcha.converter.class%
        tags:
            - {name: ezpublish.storageEngine.legacy.converter, alias: recaptcha}

# xrowgis
    xrow_field_types.xrowgis:
        class: %xrow_field_types.xrowgis.class%
        parent: ezpublish.fieldType
        tags:
            - {name: ezpublish.fieldType, alias: xrowgis}
    xrow_field_types.xrowgis.converter:
        class: %xrow_field_types.xrowgis.converter.class%
        tags:
            - {name: ezpublish.storageEngine.legacy.converter, alias: xrowgis}
    xrow_field_types.xrowgis.externalStorage:
        class: %xrow_field_types.xrowgis.externalStorage.class%
        tags:
            - {name: ezpublish.fieldType.externalStorageHandler, alias: xrowgis}
    xrow_field_types.xrowgis.storage_gateway:
        class: %xrow_field_types.xrowgis.storage_gateway.class%
        tags:
            - {name: ezpublish.fieldType.externalStorageHandler.gateway, alias: xrowgis, identifier: LegacyStorage}

# hmregexpline
    xrow_field_types.hmregexpline:
        class: %xrow_field_types.hmregexpline.class%
        parent: ezpublish.fieldType
        tags:
            - {name: ezpublish.fieldType, alias: hmregexpline}
    xrow_field_types.hmregexpline.converter:
        class: %xrow_field_types.hmregexpline.converter.class%
        tags:
            - {name: ezpublish.storageEngine.legacy.converter, alias: hmregexpline}

# xrownoderelation
    xrow_field_types.xrownoderelation:
        class: %xrow_field_types.xrownoderelation.class%
        parent: ezpublish.fieldType
        tags:
            - {name: ezpublish.fieldType, alias: xrownoderelation}
    xrow_field_types.xrownoderelation.converter:
        class: %xrow_field_types.xrownoderelation.converter.class%
        tags:
            - {name: ezpublish.storageEngine.legacy.converter, alias: xrownoderelation}